// module 1

var _ = require('lodash');

var people = [{
    "id": 1,
    "first_name": "Lillian",
    "last_name": "Kim",
    "email": "lkim0@illinois.edu",
    "gender": "Female",
    "ip_address": "190.157.239.34"
}, {
    "id": 2,
    "first_name": "Russell",
    "last_name": "Perez",
    "email": "rperez1@cdbaby.com",
    "gender": "Male",
    "ip_address": "224.181.77.10"
}, {
    "id": 3,
    "first_name": "Steven",
    "last_name": "Robinson",
    "email": "srobinson2@google.com",
    "gender": "Male",
    "ip_address": "44.202.157.2"
}, {
    "id": 4,
    "first_name": "Justin",
    "last_name": "Jacobs",
    "email": "jjacobs3@51.la",
    "gender": "Male",
    "ip_address": "19.201.113.191"
}, {
    "id": 5,
    "first_name": "Rachel",
    "last_name": "Ruiz",
    "email": "rruiz4@google.pl",
    "gender": "Female",
    "ip_address": "121.219.11.254"
}, {
    "id": 6,
    "first_name": "Evelyn",
    "last_name": "Sims",
    "email": "esims5@shutterfly.com",
    "gender": "Female",
    "ip_address": "120.207.173.243"
}, {
    "id": 7,
    "first_name": "Bobby",
    "last_name": "Henderson",
    "email": "bhenderson6@linkedin.com",
    "gender": "Male",
    "ip_address": "91.106.9.159"
}, {
    "id": 8,
    "first_name": "Anne",
    "last_name": "Tucker",
    "email": "atucker7@last.fm",
    "gender": "Female",
    "ip_address": "229.198.69.93"
}, {
    "id": 9,
    "first_name": "Annie",
    "last_name": "Kim",
    "email": "akim8@hibu.com",
    "gender": "Female",
    "ip_address": "52.96.67.235"
}, {
    "id": 10,
    "first_name": "Jason",
    "last_name": "Montgomery",
    "email": "jmontgomery9@phpbb.com",
    "gender": "Male",
    "ip_address": "71.53.235.116"
}, {
    "id": 11,
    "first_name": "Eugene",
    "last_name": "Hughes",
    "email": "ehughesa@pbs.org",
    "gender": "Male",
    "ip_address": "8.227.176.159"
}, {
    "id": 12,
    "first_name": "Denise",
    "last_name": "Ryan",
    "email": "dryanb@vinaora.com",
    "gender": "Female",
    "ip_address": "224.58.134.50"
}, {
    "id": 13,
    "first_name": "Ralph",
    "last_name": "Stevens",
    "email": "rstevensc@acquirethisname.com",
    "gender": "Male",
    "ip_address": "96.126.193.28"
}, {
    "id": 14,
    "first_name": "Keith",
    "last_name": "Tucker",
    "email": "ktuckerd@netlog.com",
    "gender": "Male",
    "ip_address": "156.153.208.206"
}, {
    "id": 15,
    "first_name": "Rachel",
    "last_name": "Hudson",
    "email": "rhudsone@timesonline.co.uk",
    "gender": "Female",
    "ip_address": "18.205.212.85"
}, {
    "id": 16,
    "first_name": "Jonathan",
    "last_name": "King",
    "email": "jkingf@bizjournals.com",
    "gender": "Male",
    "ip_address": "133.119.50.249"
}, {
    "id": 17,
    "first_name": "Clarence",
    "last_name": "Frazier",
    "email": "cfrazierg@histats.com",
    "gender": "Male",
    "ip_address": "155.188.42.139"
}, {
    "id": 18,
    "first_name": "Benjamin",
    "last_name": "Chapman",
    "email": "bchapmanh@huffingtonpost.com",
    "gender": "Male",
    "ip_address": "243.185.80.196"
}, {
    "id": 19,
    "first_name": "Angela",
    "last_name": "Cunningham",
    "email": "acunninghami@accuweather.com",
    "gender": "Female",
    "ip_address": "118.3.174.200"
}, {
    "id": 20,
    "first_name": "Linda",
    "last_name": "Chavez",
    "email": "lchavezj@discuz.net",
    "gender": "Female",
    "ip_address": "136.25.203.125"
}]

var femaleCount = _.filter(people, { gender: 'Female' }).length;
alert(femaleCount + " females!");

console.log("module 2 stuff");